<?php get_header();
function ss_card_real($p){$id=$p->get_id();$img=ss_img($id);$cats=wc_get_product_category_list($id,' · ');$min=get_post_meta($id,'_ss_price_min',true);$max=get_post_meta($id,'_ss_price_max',true);echo '<article class="product"><a href="'.esc_url(get_permalink($id)).'"><div class="ph">'.($img?'<img class="realimg" src="'.esc_url($img).'" alt="'.esc_attr($p->get_name()).'">':'').'</div><div class="pi"><h3>'.esc_html($p->get_name()).'</h3><div class="meta">'.wp_strip_all_tags($cats).'</div><div class="price">€'.esc_html($min).' – €'.esc_html($max).'</div></div></a></article>';}
if(is_singular('product')):
 global $post; $p=wc_get_product($post->ID); $img=ss_img($p->get_id()); $scales=ss_scales($p); $min=get_post_meta($p->get_id(),'_ss_price_min',true);$max=get_post_meta($p->get_id(),'_ss_price_max',true); ?>
<main><div class="wrap"><div class="crumb" style="padding-top:28px">Home / <?php echo wp_strip_all_tags(wc_get_product_category_list($p->get_id(),' / ')); ?> / <?php echo esc_html($p->get_name()); ?></div><div class="product-layout"><div><div class="gallery-main"><?php if($img): ?><img src="<?php echo esc_url($img); ?>" alt="<?php echo esc_attr($p->get_name()); ?>"><?php endif; ?></div><div class="thumbs"><?php for($i=0;$i<4;$i++): ?><div class="thumb"><?php if($img): ?><img src="<?php echo esc_url($img); ?>"><?php endif; ?></div><?php endfor; ?></div></div><div class="buy"><div class="eyebrow"><?php echo wp_strip_all_tags(wc_get_product_category_list($p->get_id(),' · ')); ?> · Resin kit</div><h1><?php echo esc_html($p->get_name()); ?></h1><div class="buy-price">€<?php echo esc_html($min); ?> – €<?php echo esc_html($max); ?></div><div class="stock">● In stock</div><div class="scale-title">Select scale</div><div class="scales"><?php foreach($scales as $s): ?><button class="scale"><?php echo esc_html($s); ?></button><?php endforeach; ?></div><div class="addrow"><input class="qty" value="1"><button class="add">ADD TO CART</button></div><div class="bullets"><?php echo wp_kses_post(wpautop($p->get_short_description())); ?></div><div class="accordion"><div>Product Details <b>+</b></div><div>What's Included <b>+</b></div><div>Assembly & Painting <b>+</b></div><div>Shipping & Returns <b>+</b></div></div></div></div></div><section class="section light-section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">You may also like</div><h2>RELATED PRODUCTS.</h2></div></div><div class="products"><?php foreach(wc_get_products(['limit'=>3,'exclude'=>[$p->get_id()],'status'=>'publish']) as $rp) ss_card_real($rp); ?></div></div></section></main>
<?php else: $view=isset($_GET['ss'])?sanitize_key($_GET['ss']):'home';
$all=wc_get_products(['limit'=>12,'status'=>'publish','orderby'=>'date','order'=>'DESC']);
if($view==='home'): ?>
<main><section class="hero"><div class="wrap hero-in"><div class="eyebrow">Speedstar Models · Scale Model Studio</div><h1>DETAILS THAT<br>CHANGE THE BUILD.</h1><p>Resin parts for automotive scale models. Bodykits, wheels, engines and accessories engineered for builders who care about the last millimetre.</p><a class="btn" href="/?ss=shop">EXPLORE PRODUCTS</a></div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Shop by category</div><h2>BUILD YOUR NEXT PROJECT.</h2></div></div><div class="cat-grid"><a class="cat" data-mark="B" href="/?ss=bodykits"><strong>Bodykits</strong><small>Widebody · Aero · Conversions</small></a><a class="cat" data-mark="W" href="/?ss=wheels"><strong>Wheels</strong><small>Street · Racing · Classic</small></a><a class="cat" data-mark="E" href="/?ss=engines"><strong>Engines</strong><small>Detailed resin engine kits</small></a><a class="cat" data-mark="A" href="/?ss=shop"><strong>Accessories</strong><small>Details that finish the build</small></a></div></div></section><section class="section light-section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Fresh from the workshop</div><h2>LATEST PRODUCTS.</h2></div></div><div class="products"><?php foreach(array_slice($all,0,4) as $pp) ss_card_real($pp); ?></div></div></section></main>
<?php elseif(in_array($view,['shop','bodykits','wheels','engines','merch'])): $title=$view==='shop'?'Shop':ucfirst($view); $category_slug=$view==='merch'?'t-shirts':$view; $products=$view==='shop'?$all:wc_get_products(['limit'=>12,'status'=>'publish','category'=>[$category_slug]]); ?>
<main><section class="pagehero"><div class="wrap"><div class="crumb">Home / <?php echo esc_html($title); ?></div><h1><?php echo esc_html(strtoupper($title)); ?>.</h1></div></section><section class="section"><div class="wrap"><div class="filters"><span class="chip on">All</span><span class="chip">1:24</span><span class="chip">1:18</span><?php if($view==='engines'): ?><span class="chip">1:12</span><span class="chip">1:10</span><span class="chip">1:8</span><?php endif; ?></div><div class="products"><?php foreach($products as $pp) ss_card_real($pp); ?></div></div></section></main>
<?php elseif($view==='about'): ?><main><section class="pagehero"><div class="wrap"><div class="crumb">Home / About</div><h1>BUILT FOR BUILDERS.</h1></div></section><section class="section"><div class="wrap about-grid"><div class="about-copy"><div class="eyebrow">Speedstar Models</div><h2>SMALL PARTS.<br>BIG DIFFERENCE.</h2><p>Resin components for automotive scale-model builders: bodykits, wheels, engines, figures and accessories designed to turn a standard kit into something personal.</p></div><div class="about-stat"><div class="stat"><strong>1:24</strong><span>Core scale</span></div><div class="stat"><strong>1:18</strong><span>Core scale</span></div><div class="stat"><strong>5</strong><span>Engine scale options</span></div><div class="stat"><strong>EU</strong><span>Built in Portugal</span></div></div></div></section></main>
<?php endif; endif; get_footer(); ?>