<?php get_header();
$view=isset($_GET['ss'])?sanitize_key($_GET['ss']):'home';
$all=wc_get_products(['limit'=>12,'status'=>'publish','orderby'=>'date','order'=>'DESC']);
if($view==='home'): ?><main><section class="hero hero-rotator" aria-label="Featured products">
<div class="hero-slide hero-slide-1 active" aria-hidden="false"><div class="wrap hero-in"><div class="eyebrow">Bodykits · Resin parts</div><h1>BUILD IT<br>WIDER.</h1><p>Nissan Silvia S13 Spirit Rei Miyabi widebody kit. A complete resin conversion for a more aggressive scale build.</p><a class="btn" href="/?ss=bodykits">EXPLORE BODYKITS</a></div></div>
<div class="hero-slide hero-slide-2" aria-hidden="true"><div class="wrap hero-in"><div class="eyebrow">Wheels · 1:18 & 1:24</div><h1>STANCE STARTS<br>HERE.</h1><p>Enkei GTC02 19” with sport tires. Detailed resin wheels for clean, performance-focused builds.</p><a class="btn" href="/?ss=wheels">EXPLORE WHEELS</a></div></div>
<div class="hero-slide hero-slide-3" aria-hidden="true"><div class="wrap hero-in"><div class="eyebrow">Engines · Multi-scale</div><h1>DETAILS UNDER<br>THE SKIN.</h1><p>Ford Cosworth V8 DFV F1 engine. High-detail resin components for builders who want the mechanical story too.</p><a class="btn" href="/?ss=engines">EXPLORE ENGINES</a></div></div>
<button class="hero-arrow hero-prev" type="button" aria-label="Previous slide">‹</button><button class="hero-arrow hero-next" type="button" aria-label="Next slide">›</button><div class="hero-dots"><button class="hero-dot active" type="button" aria-label="Slide 1" aria-current="true"></button><button class="hero-dot" type="button" aria-label="Slide 2"></button><button class="hero-dot" type="button" aria-label="Slide 3"></button></div>
</section><section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Shop by category</div><h2>BUILD YOUR NEXT PROJECT.</h2></div></div><div class="cat-grid cat-grid-photo">
<a class="cat cat-photo" href="/?ss=bodykits" style="--cat-img:url('https://i0.wp.com/speedstarmodels.com/wp-content/uploads/2025/11/il_794xN.6924719895_12ly.jpg?fit=794%2C528&ssl=1')"><span class="cat-copy"><strong>Bodykits</strong><small>Nissan Silvia S13 Spirit Rei Miyabi</small><em>View Bodykits →</em></span></a>
<a class="cat cat-photo" href="/?ss=wheels" style="--cat-img:url('https://i0.wp.com/speedstarmodels.com/wp-content/uploads/2025/12/enkei_gtc02.jpg?fit=1920%2C1538&ssl=1')"><span class="cat-copy"><strong>Wheels</strong><small>Enkei GTC02 19” with sport tires</small><em>View Wheels →</em></span></a>
<a class="cat cat-photo" href="/?ss=engines" style="--cat-img:url('https://i0.wp.com/speedstarmodels.com/wp-content/uploads/2025/11/il_794xN.6164545748_6blb.jpg?fit=794%2C818&ssl=1')"><span class="cat-copy"><strong>Engines</strong><small>Ford Cosworth V8 DFV F1 Engine</small><em>View Engines →</em></span></a>
<a class="cat cat-photo" href="/?ss=merch" style="--cat-img:url('https://i0.wp.com/speedstarmodels.com/wp-content/uploads/2025/11/nissan-r33-nismo.jpg?fit=2000%2C2000&ssl=1')"><span class="cat-copy"><strong>Merch</strong><small>Nissan Skyline R33 GT-R NISMO Legend</small><em>View Merch →</em></span></a>
</div></div></section><section class="section latest-section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Fresh from the workshop</div><h2>LATEST PRODUCTS.</h2></div><a href="/?ss=shop">VIEW ALL PRODUCTS →</a></div><div class="products"><?php foreach(array_slice($all,0,4) as $pp) ss_card_real($pp); ?></div></div></section></main>
<?php elseif(in_array($view,['shop','bodykits','wheels','engines','merch'])): $title=$view==='shop'?'Shop':ucfirst($view); $category_slug=$view==='merch'?'t-shirts':$view; $products=$view==='shop'?$all:wc_get_products(['limit'=>12,'status'=>'publish','category'=>[$category_slug]]); ?>
<main><section class="pagehero"><div class="wrap"><div class="crumb">Home / <?php echo esc_html($title); ?></div><h1><?php echo esc_html(strtoupper($title)); ?>.</h1></div></section><section class="section"><div class="wrap"><div class="filters" aria-label="Filter by scale"><button class="chip ss-filter on" type="button" data-scale="all">All</button><button class="chip ss-filter" type="button" data-scale="124">1:24</button><button class="chip ss-filter" type="button" data-scale="118">1:18</button><?php if($view==='engines'): ?><button class="chip ss-filter" type="button" data-scale="112">1:12</button><button class="chip ss-filter" type="button" data-scale="110">1:10</button><button class="chip ss-filter" type="button" data-scale="18">1:8</button><?php endif; ?></div><div class="products"><?php foreach($products as $pp) ss_card_real($pp); ?></div></div></section></main>
<?php elseif($view==='about'): ?><main><section class="pagehero"><div class="wrap"><div class="crumb">Home / About</div><h1>BUILT FOR BUILDERS.</h1></div></section><section class="section"><div class="wrap about-grid"><div class="about-copy"><div class="eyebrow">Speedstar Models</div><h2>SMALL PARTS.<br>BIG DIFFERENCE.</h2><p>Resin components for automotive scale-model builders: bodykits, wheels, engines, figures and accessories designed to turn a standard kit into something personal.</p></div><div class="about-stat"><div class="stat"><strong>1:24</strong><span>Core scale</span></div><div class="stat"><strong>1:18</strong><span>Core scale</span></div><div class="stat"><strong>5</strong><span>Engine scale options</span></div><div class="stat"><strong>EU</strong><span>Built in Portugal</span></div></div></div></section></main>
<?php endif; get_footer(); ?>